// Generated by `npm run i18n:sync` from the folders next to this file. Do not edit.
import f0 from "./ar/alternatives/5sim.json";
import f1 from "./ar/alternatives/onlinesim.json";
import f2 from "./ar/alternatives/sms-activate-org.json";
import f3 from "./ar/alternatives/sms-man.json";
import f4 from "./ar/alternatives/textverified.json";
import f5 from "./ar/alternatives-ui.json";
import f6 from "./ar/blog/esim-vs-virtual-number.json";
import f7 from "./ar/blog/google-account-without-phone-number.json";
import f8 from "./ar/blog/how-to-receive-sms-online.json";
import f9 from "./ar/blog/second-whatsapp-account.json";
import f10 from "./ar/blog/telegram-without-phone-number.json";
import f11 from "./ar/blog/virtual-number-for-dating-apps.json";
import f12 from "./ar/blog/what-is-a-virtual-phone-number.json";
import f13 from "./ar/blog-ui.json";
import f14 from "./ar/countries/brazil.json";
import f15 from "./ar/countries/canada.json";
import f16 from "./ar/countries/france.json";
import f17 from "./ar/countries/germany.json";
import f18 from "./ar/countries/india.json";
import f19 from "./ar/countries/indonesia.json";
import f20 from "./ar/countries/italy.json";
import f21 from "./ar/countries/kazakhstan.json";
import f22 from "./ar/countries/mexico.json";
import f23 from "./ar/countries/netherlands.json";
import f24 from "./ar/countries/philippines.json";
import f25 from "./ar/countries/poland.json";
import f26 from "./ar/countries/portugal.json";
import f27 from "./ar/countries/spain.json";
import f28 from "./ar/countries/thailand.json";
import f29 from "./ar/countries/turkey.json";
import f30 from "./ar/countries/ukraine.json";
import f31 from "./ar/countries/united-kingdom.json";
import f32 from "./ar/countries/united-states.json";
import f33 from "./ar/countries/vietnam.json";
import f34 from "./ar/help/account-balance.json";
import f35 from "./ar/help/activation-issues.json";
import f36 from "./ar/help/billing-coins-refunds.json";
import f37 from "./ar/help/choosing-country.json";
import f38 from "./ar/home.json";
import f39 from "./ar/privacy.json";
import f40 from "./ar/services/adidas.json";
import f41 from "./ar/services/airbnb.json";
import f42 from "./ar/services/aliexpress.json";
import f43 from "./ar/services/apple.json";
import f44 from "./ar/services/binance.json";
import f45 from "./ar/services/cursor.json";
import f46 from "./ar/services/discord.json";
import f47 from "./ar/services/ebay.json";
import f48 from "./ar/services/facebook.json";
import f49 from "./ar/services/fiverr.json";
import f50 from "./ar/services/google.json";
import f51 from "./ar/services/grab.json";
import f52 from "./ar/services/instagram.json";
import f53 from "./ar/services/kakaotalk.json";
import f54 from "./ar/services/line.json";
import f55 from "./ar/services/netflix.json";
import f56 from "./ar/services/paypal.json";
import f57 from "./ar/services/reddit.json";
import f58 from "./ar/services/shopee.json";
import f59 from "./ar/services/signal.json";
import f60 from "./ar/services/snapchat.json";
import f61 from "./ar/services/steam.json";
import f62 from "./ar/services/telegram.json";
import f63 from "./ar/services/tiktok.json";
import f64 from "./ar/services/tinder.json";
import f65 from "./ar/services/twitch.json";
import f66 from "./ar/services/twitter.json";
import f67 from "./ar/services/uber.json";
import f68 from "./ar/services/viber.json";
import f69 from "./ar/services/vkcom.json";
import f70 from "./ar/services/wechat.json";
import f71 from "./ar/services/whatsapp.json";
import f72 from "./ar/services/zalo.json";
import f73 from "./ar/services-ui.json";
import f74 from "./ar/support.json";
import f75 from "./ar/terms.json";
import f76 from "./ar/ui.json";
import f77 from "./en/alternatives/5sim.json";
import f78 from "./en/alternatives/onlinesim.json";
import f79 from "./en/alternatives/sms-activate-org.json";
import f80 from "./en/alternatives/sms-man.json";
import f81 from "./en/alternatives/textverified.json";
import f82 from "./en/alternatives-ui.json";
import f83 from "./en/blog/esim-vs-virtual-number.json";
import f84 from "./en/blog/google-account-without-phone-number.json";
import f85 from "./en/blog/how-to-receive-sms-online.json";
import f86 from "./en/blog/second-whatsapp-account.json";
import f87 from "./en/blog/telegram-without-phone-number.json";
import f88 from "./en/blog/virtual-number-for-dating-apps.json";
import f89 from "./en/blog/what-is-a-virtual-phone-number.json";
import f90 from "./en/blog-ui.json";
import f91 from "./en/countries/brazil.json";
import f92 from "./en/countries/canada.json";
import f93 from "./en/countries/france.json";
import f94 from "./en/countries/germany.json";
import f95 from "./en/countries/india.json";
import f96 from "./en/countries/indonesia.json";
import f97 from "./en/countries/italy.json";
import f98 from "./en/countries/kazakhstan.json";
import f99 from "./en/countries/mexico.json";
import f100 from "./en/countries/netherlands.json";
import f101 from "./en/countries/philippines.json";
import f102 from "./en/countries/poland.json";
import f103 from "./en/countries/portugal.json";
import f104 from "./en/countries/spain.json";
import f105 from "./en/countries/thailand.json";
import f106 from "./en/countries/turkey.json";
import f107 from "./en/countries/ukraine.json";
import f108 from "./en/countries/united-kingdom.json";
import f109 from "./en/countries/united-states.json";
import f110 from "./en/countries/vietnam.json";
import f111 from "./en/help/account-balance.json";
import f112 from "./en/help/activation-issues.json";
import f113 from "./en/help/billing-coins-refunds.json";
import f114 from "./en/help/choosing-country.json";
import f115 from "./en/home.json";
import f116 from "./en/privacy.json";
import f117 from "./en/services/adidas.json";
import f118 from "./en/services/airbnb.json";
import f119 from "./en/services/aliexpress.json";
import f120 from "./en/services/apple.json";
import f121 from "./en/services/binance.json";
import f122 from "./en/services/cursor.json";
import f123 from "./en/services/discord.json";
import f124 from "./en/services/ebay.json";
import f125 from "./en/services/facebook.json";
import f126 from "./en/services/fiverr.json";
import f127 from "./en/services/google.json";
import f128 from "./en/services/grab.json";
import f129 from "./en/services/instagram.json";
import f130 from "./en/services/kakaotalk.json";
import f131 from "./en/services/line.json";
import f132 from "./en/services/netflix.json";
import f133 from "./en/services/paypal.json";
import f134 from "./en/services/reddit.json";
import f135 from "./en/services/shopee.json";
import f136 from "./en/services/signal.json";
import f137 from "./en/services/snapchat.json";
import f138 from "./en/services/steam.json";
import f139 from "./en/services/telegram.json";
import f140 from "./en/services/tiktok.json";
import f141 from "./en/services/tinder.json";
import f142 from "./en/services/twitch.json";
import f143 from "./en/services/twitter.json";
import f144 from "./en/services/uber.json";
import f145 from "./en/services/viber.json";
import f146 from "./en/services/vkcom.json";
import f147 from "./en/services/wechat.json";
import f148 from "./en/services/whatsapp.json";
import f149 from "./en/services/zalo.json";
import f150 from "./en/services-ui.json";
import f151 from "./en/support.json";
import f152 from "./en/terms.json";
import f153 from "./en/ui.json";
import f154 from "./es/alternatives/5sim.json";
import f155 from "./es/alternatives/onlinesim.json";
import f156 from "./es/alternatives/sms-activate-org.json";
import f157 from "./es/alternatives/sms-man.json";
import f158 from "./es/alternatives/textverified.json";
import f159 from "./es/alternatives-ui.json";
import f160 from "./es/blog/esim-vs-virtual-number.json";
import f161 from "./es/blog/google-account-without-phone-number.json";
import f162 from "./es/blog/how-to-receive-sms-online.json";
import f163 from "./es/blog/second-whatsapp-account.json";
import f164 from "./es/blog/telegram-without-phone-number.json";
import f165 from "./es/blog/virtual-number-for-dating-apps.json";
import f166 from "./es/blog/what-is-a-virtual-phone-number.json";
import f167 from "./es/blog-ui.json";
import f168 from "./es/countries/brazil.json";
import f169 from "./es/countries/canada.json";
import f170 from "./es/countries/france.json";
import f171 from "./es/countries/germany.json";
import f172 from "./es/countries/india.json";
import f173 from "./es/countries/indonesia.json";
import f174 from "./es/countries/italy.json";
import f175 from "./es/countries/kazakhstan.json";
import f176 from "./es/countries/mexico.json";
import f177 from "./es/countries/netherlands.json";
import f178 from "./es/countries/philippines.json";
import f179 from "./es/countries/poland.json";
import f180 from "./es/countries/portugal.json";
import f181 from "./es/countries/spain.json";
import f182 from "./es/countries/thailand.json";
import f183 from "./es/countries/turkey.json";
import f184 from "./es/countries/ukraine.json";
import f185 from "./es/countries/united-kingdom.json";
import f186 from "./es/countries/united-states.json";
import f187 from "./es/countries/vietnam.json";
import f188 from "./es/help/account-balance.json";
import f189 from "./es/help/activation-issues.json";
import f190 from "./es/help/billing-coins-refunds.json";
import f191 from "./es/help/choosing-country.json";
import f192 from "./es/home.json";
import f193 from "./es/privacy.json";
import f194 from "./es/services/adidas.json";
import f195 from "./es/services/airbnb.json";
import f196 from "./es/services/aliexpress.json";
import f197 from "./es/services/apple.json";
import f198 from "./es/services/binance.json";
import f199 from "./es/services/cursor.json";
import f200 from "./es/services/discord.json";
import f201 from "./es/services/ebay.json";
import f202 from "./es/services/facebook.json";
import f203 from "./es/services/fiverr.json";
import f204 from "./es/services/google.json";
import f205 from "./es/services/grab.json";
import f206 from "./es/services/instagram.json";
import f207 from "./es/services/kakaotalk.json";
import f208 from "./es/services/line.json";
import f209 from "./es/services/netflix.json";
import f210 from "./es/services/paypal.json";
import f211 from "./es/services/reddit.json";
import f212 from "./es/services/shopee.json";
import f213 from "./es/services/signal.json";
import f214 from "./es/services/snapchat.json";
import f215 from "./es/services/steam.json";
import f216 from "./es/services/telegram.json";
import f217 from "./es/services/tiktok.json";
import f218 from "./es/services/tinder.json";
import f219 from "./es/services/twitch.json";
import f220 from "./es/services/twitter.json";
import f221 from "./es/services/uber.json";
import f222 from "./es/services/viber.json";
import f223 from "./es/services/vkcom.json";
import f224 from "./es/services/wechat.json";
import f225 from "./es/services/whatsapp.json";
import f226 from "./es/services/zalo.json";
import f227 from "./es/services-ui.json";
import f228 from "./es/support.json";
import f229 from "./es/terms.json";
import f230 from "./es/ui.json";
import f231 from "./fr/alternatives/5sim.json";
import f232 from "./fr/alternatives/onlinesim.json";
import f233 from "./fr/alternatives/sms-activate-org.json";
import f234 from "./fr/alternatives/sms-man.json";
import f235 from "./fr/alternatives/textverified.json";
import f236 from "./fr/alternatives-ui.json";
import f237 from "./fr/blog/esim-vs-virtual-number.json";
import f238 from "./fr/blog/google-account-without-phone-number.json";
import f239 from "./fr/blog/how-to-receive-sms-online.json";
import f240 from "./fr/blog/second-whatsapp-account.json";
import f241 from "./fr/blog/telegram-without-phone-number.json";
import f242 from "./fr/blog/virtual-number-for-dating-apps.json";
import f243 from "./fr/blog/what-is-a-virtual-phone-number.json";
import f244 from "./fr/blog-ui.json";
import f245 from "./fr/countries/brazil.json";
import f246 from "./fr/countries/canada.json";
import f247 from "./fr/countries/france.json";
import f248 from "./fr/countries/germany.json";
import f249 from "./fr/countries/india.json";
import f250 from "./fr/countries/indonesia.json";
import f251 from "./fr/countries/italy.json";
import f252 from "./fr/countries/kazakhstan.json";
import f253 from "./fr/countries/mexico.json";
import f254 from "./fr/countries/netherlands.json";
import f255 from "./fr/countries/philippines.json";
import f256 from "./fr/countries/poland.json";
import f257 from "./fr/countries/portugal.json";
import f258 from "./fr/countries/spain.json";
import f259 from "./fr/countries/thailand.json";
import f260 from "./fr/countries/turkey.json";
import f261 from "./fr/countries/ukraine.json";
import f262 from "./fr/countries/united-kingdom.json";
import f263 from "./fr/countries/united-states.json";
import f264 from "./fr/countries/vietnam.json";
import f265 from "./fr/help/account-balance.json";
import f266 from "./fr/help/activation-issues.json";
import f267 from "./fr/help/billing-coins-refunds.json";
import f268 from "./fr/help/choosing-country.json";
import f269 from "./fr/home.json";
import f270 from "./fr/privacy.json";
import f271 from "./fr/services/adidas.json";
import f272 from "./fr/services/airbnb.json";
import f273 from "./fr/services/aliexpress.json";
import f274 from "./fr/services/apple.json";
import f275 from "./fr/services/binance.json";
import f276 from "./fr/services/cursor.json";
import f277 from "./fr/services/discord.json";
import f278 from "./fr/services/ebay.json";
import f279 from "./fr/services/facebook.json";
import f280 from "./fr/services/fiverr.json";
import f281 from "./fr/services/google.json";
import f282 from "./fr/services/grab.json";
import f283 from "./fr/services/instagram.json";
import f284 from "./fr/services/kakaotalk.json";
import f285 from "./fr/services/line.json";
import f286 from "./fr/services/netflix.json";
import f287 from "./fr/services/paypal.json";
import f288 from "./fr/services/reddit.json";
import f289 from "./fr/services/shopee.json";
import f290 from "./fr/services/signal.json";
import f291 from "./fr/services/snapchat.json";
import f292 from "./fr/services/steam.json";
import f293 from "./fr/services/telegram.json";
import f294 from "./fr/services/tiktok.json";
import f295 from "./fr/services/tinder.json";
import f296 from "./fr/services/twitch.json";
import f297 from "./fr/services/twitter.json";
import f298 from "./fr/services/uber.json";
import f299 from "./fr/services/viber.json";
import f300 from "./fr/services/vkcom.json";
import f301 from "./fr/services/wechat.json";
import f302 from "./fr/services/whatsapp.json";
import f303 from "./fr/services/zalo.json";
import f304 from "./fr/services-ui.json";
import f305 from "./fr/support.json";
import f306 from "./fr/terms.json";
import f307 from "./fr/ui.json";
import f308 from "./hi/alternatives/5sim.json";
import f309 from "./hi/alternatives/onlinesim.json";
import f310 from "./hi/alternatives/sms-activate-org.json";
import f311 from "./hi/alternatives/sms-man.json";
import f312 from "./hi/alternatives/textverified.json";
import f313 from "./hi/alternatives-ui.json";
import f314 from "./hi/blog/esim-vs-virtual-number.json";
import f315 from "./hi/blog/google-account-without-phone-number.json";
import f316 from "./hi/blog/how-to-receive-sms-online.json";
import f317 from "./hi/blog/second-whatsapp-account.json";
import f318 from "./hi/blog/telegram-without-phone-number.json";
import f319 from "./hi/blog/virtual-number-for-dating-apps.json";
import f320 from "./hi/blog/what-is-a-virtual-phone-number.json";
import f321 from "./hi/blog-ui.json";
import f322 from "./hi/countries/brazil.json";
import f323 from "./hi/countries/canada.json";
import f324 from "./hi/countries/france.json";
import f325 from "./hi/countries/germany.json";
import f326 from "./hi/countries/india.json";
import f327 from "./hi/countries/indonesia.json";
import f328 from "./hi/countries/italy.json";
import f329 from "./hi/countries/kazakhstan.json";
import f330 from "./hi/countries/mexico.json";
import f331 from "./hi/countries/netherlands.json";
import f332 from "./hi/countries/philippines.json";
import f333 from "./hi/countries/poland.json";
import f334 from "./hi/countries/portugal.json";
import f335 from "./hi/countries/spain.json";
import f336 from "./hi/countries/thailand.json";
import f337 from "./hi/countries/turkey.json";
import f338 from "./hi/countries/ukraine.json";
import f339 from "./hi/countries/united-kingdom.json";
import f340 from "./hi/countries/united-states.json";
import f341 from "./hi/countries/vietnam.json";
import f342 from "./hi/help/account-balance.json";
import f343 from "./hi/help/activation-issues.json";
import f344 from "./hi/help/billing-coins-refunds.json";
import f345 from "./hi/help/choosing-country.json";
import f346 from "./hi/home.json";
import f347 from "./hi/privacy.json";
import f348 from "./hi/services/adidas.json";
import f349 from "./hi/services/airbnb.json";
import f350 from "./hi/services/aliexpress.json";
import f351 from "./hi/services/apple.json";
import f352 from "./hi/services/binance.json";
import f353 from "./hi/services/cursor.json";
import f354 from "./hi/services/discord.json";
import f355 from "./hi/services/ebay.json";
import f356 from "./hi/services/facebook.json";
import f357 from "./hi/services/fiverr.json";
import f358 from "./hi/services/google.json";
import f359 from "./hi/services/grab.json";
import f360 from "./hi/services/instagram.json";
import f361 from "./hi/services/kakaotalk.json";
import f362 from "./hi/services/line.json";
import f363 from "./hi/services/netflix.json";
import f364 from "./hi/services/paypal.json";
import f365 from "./hi/services/reddit.json";
import f366 from "./hi/services/shopee.json";
import f367 from "./hi/services/signal.json";
import f368 from "./hi/services/snapchat.json";
import f369 from "./hi/services/steam.json";
import f370 from "./hi/services/telegram.json";
import f371 from "./hi/services/tiktok.json";
import f372 from "./hi/services/tinder.json";
import f373 from "./hi/services/twitch.json";
import f374 from "./hi/services/twitter.json";
import f375 from "./hi/services/uber.json";
import f376 from "./hi/services/viber.json";
import f377 from "./hi/services/vkcom.json";
import f378 from "./hi/services/wechat.json";
import f379 from "./hi/services/whatsapp.json";
import f380 from "./hi/services/zalo.json";
import f381 from "./hi/services-ui.json";
import f382 from "./hi/support.json";
import f383 from "./hi/terms.json";
import f384 from "./hi/ui.json";
import f385 from "./id/alternatives/5sim.json";
import f386 from "./id/alternatives/onlinesim.json";
import f387 from "./id/alternatives/sms-activate-org.json";
import f388 from "./id/alternatives/sms-man.json";
import f389 from "./id/alternatives/textverified.json";
import f390 from "./id/alternatives-ui.json";
import f391 from "./id/blog/esim-vs-virtual-number.json";
import f392 from "./id/blog/google-account-without-phone-number.json";
import f393 from "./id/blog/how-to-receive-sms-online.json";
import f394 from "./id/blog/second-whatsapp-account.json";
import f395 from "./id/blog/telegram-without-phone-number.json";
import f396 from "./id/blog/virtual-number-for-dating-apps.json";
import f397 from "./id/blog/what-is-a-virtual-phone-number.json";
import f398 from "./id/blog-ui.json";
import f399 from "./id/countries/brazil.json";
import f400 from "./id/countries/canada.json";
import f401 from "./id/countries/france.json";
import f402 from "./id/countries/germany.json";
import f403 from "./id/countries/india.json";
import f404 from "./id/countries/indonesia.json";
import f405 from "./id/countries/italy.json";
import f406 from "./id/countries/kazakhstan.json";
import f407 from "./id/countries/mexico.json";
import f408 from "./id/countries/netherlands.json";
import f409 from "./id/countries/philippines.json";
import f410 from "./id/countries/poland.json";
import f411 from "./id/countries/portugal.json";
import f412 from "./id/countries/spain.json";
import f413 from "./id/countries/thailand.json";
import f414 from "./id/countries/turkey.json";
import f415 from "./id/countries/ukraine.json";
import f416 from "./id/countries/united-kingdom.json";
import f417 from "./id/countries/united-states.json";
import f418 from "./id/countries/vietnam.json";
import f419 from "./id/help/account-balance.json";
import f420 from "./id/help/activation-issues.json";
import f421 from "./id/help/billing-coins-refunds.json";
import f422 from "./id/help/choosing-country.json";
import f423 from "./id/home.json";
import f424 from "./id/privacy.json";
import f425 from "./id/services/adidas.json";
import f426 from "./id/services/airbnb.json";
import f427 from "./id/services/aliexpress.json";
import f428 from "./id/services/apple.json";
import f429 from "./id/services/binance.json";
import f430 from "./id/services/cursor.json";
import f431 from "./id/services/discord.json";
import f432 from "./id/services/ebay.json";
import f433 from "./id/services/facebook.json";
import f434 from "./id/services/fiverr.json";
import f435 from "./id/services/google.json";
import f436 from "./id/services/grab.json";
import f437 from "./id/services/instagram.json";
import f438 from "./id/services/kakaotalk.json";
import f439 from "./id/services/line.json";
import f440 from "./id/services/netflix.json";
import f441 from "./id/services/paypal.json";
import f442 from "./id/services/reddit.json";
import f443 from "./id/services/shopee.json";
import f444 from "./id/services/signal.json";
import f445 from "./id/services/snapchat.json";
import f446 from "./id/services/steam.json";
import f447 from "./id/services/telegram.json";
import f448 from "./id/services/tiktok.json";
import f449 from "./id/services/tinder.json";
import f450 from "./id/services/twitch.json";
import f451 from "./id/services/twitter.json";
import f452 from "./id/services/uber.json";
import f453 from "./id/services/viber.json";
import f454 from "./id/services/vkcom.json";
import f455 from "./id/services/wechat.json";
import f456 from "./id/services/whatsapp.json";
import f457 from "./id/services/zalo.json";
import f458 from "./id/services-ui.json";
import f459 from "./id/support.json";
import f460 from "./id/terms.json";
import f461 from "./id/ui.json";
import f462 from "./pt/alternatives/5sim.json";
import f463 from "./pt/alternatives/onlinesim.json";
import f464 from "./pt/alternatives/sms-activate-org.json";
import f465 from "./pt/alternatives/sms-man.json";
import f466 from "./pt/alternatives/textverified.json";
import f467 from "./pt/alternatives-ui.json";
import f468 from "./pt/blog/esim-vs-virtual-number.json";
import f469 from "./pt/blog/google-account-without-phone-number.json";
import f470 from "./pt/blog/how-to-receive-sms-online.json";
import f471 from "./pt/blog/second-whatsapp-account.json";
import f472 from "./pt/blog/telegram-without-phone-number.json";
import f473 from "./pt/blog/virtual-number-for-dating-apps.json";
import f474 from "./pt/blog/what-is-a-virtual-phone-number.json";
import f475 from "./pt/blog-ui.json";
import f476 from "./pt/countries/brazil.json";
import f477 from "./pt/countries/canada.json";
import f478 from "./pt/countries/france.json";
import f479 from "./pt/countries/germany.json";
import f480 from "./pt/countries/india.json";
import f481 from "./pt/countries/indonesia.json";
import f482 from "./pt/countries/italy.json";
import f483 from "./pt/countries/kazakhstan.json";
import f484 from "./pt/countries/mexico.json";
import f485 from "./pt/countries/netherlands.json";
import f486 from "./pt/countries/philippines.json";
import f487 from "./pt/countries/poland.json";
import f488 from "./pt/countries/portugal.json";
import f489 from "./pt/countries/spain.json";
import f490 from "./pt/countries/thailand.json";
import f491 from "./pt/countries/turkey.json";
import f492 from "./pt/countries/ukraine.json";
import f493 from "./pt/countries/united-kingdom.json";
import f494 from "./pt/countries/united-states.json";
import f495 from "./pt/countries/vietnam.json";
import f496 from "./pt/help/account-balance.json";
import f497 from "./pt/help/activation-issues.json";
import f498 from "./pt/help/billing-coins-refunds.json";
import f499 from "./pt/help/choosing-country.json";
import f500 from "./pt/home.json";
import f501 from "./pt/privacy.json";
import f502 from "./pt/services/adidas.json";
import f503 from "./pt/services/airbnb.json";
import f504 from "./pt/services/aliexpress.json";
import f505 from "./pt/services/apple.json";
import f506 from "./pt/services/binance.json";
import f507 from "./pt/services/cursor.json";
import f508 from "./pt/services/discord.json";
import f509 from "./pt/services/ebay.json";
import f510 from "./pt/services/facebook.json";
import f511 from "./pt/services/fiverr.json";
import f512 from "./pt/services/google.json";
import f513 from "./pt/services/grab.json";
import f514 from "./pt/services/instagram.json";
import f515 from "./pt/services/kakaotalk.json";
import f516 from "./pt/services/line.json";
import f517 from "./pt/services/netflix.json";
import f518 from "./pt/services/paypal.json";
import f519 from "./pt/services/reddit.json";
import f520 from "./pt/services/shopee.json";
import f521 from "./pt/services/signal.json";
import f522 from "./pt/services/snapchat.json";
import f523 from "./pt/services/steam.json";
import f524 from "./pt/services/telegram.json";
import f525 from "./pt/services/tiktok.json";
import f526 from "./pt/services/tinder.json";
import f527 from "./pt/services/twitch.json";
import f528 from "./pt/services/twitter.json";
import f529 from "./pt/services/uber.json";
import f530 from "./pt/services/viber.json";
import f531 from "./pt/services/vkcom.json";
import f532 from "./pt/services/wechat.json";
import f533 from "./pt/services/whatsapp.json";
import f534 from "./pt/services/zalo.json";
import f535 from "./pt/services-ui.json";
import f536 from "./pt/support.json";
import f537 from "./pt/terms.json";
import f538 from "./pt/ui.json";
import f539 from "./ru/alternatives/5sim.json";
import f540 from "./ru/alternatives/onlinesim.json";
import f541 from "./ru/alternatives/sms-activate-org.json";
import f542 from "./ru/alternatives/sms-man.json";
import f543 from "./ru/alternatives/textverified.json";
import f544 from "./ru/alternatives-ui.json";
import f545 from "./ru/blog/esim-vs-virtual-number.json";
import f546 from "./ru/blog/google-account-without-phone-number.json";
import f547 from "./ru/blog/how-to-receive-sms-online.json";
import f548 from "./ru/blog/second-whatsapp-account.json";
import f549 from "./ru/blog/telegram-without-phone-number.json";
import f550 from "./ru/blog/virtual-number-for-dating-apps.json";
import f551 from "./ru/blog/what-is-a-virtual-phone-number.json";
import f552 from "./ru/blog-ui.json";
import f553 from "./ru/countries/brazil.json";
import f554 from "./ru/countries/canada.json";
import f555 from "./ru/countries/france.json";
import f556 from "./ru/countries/germany.json";
import f557 from "./ru/countries/india.json";
import f558 from "./ru/countries/indonesia.json";
import f559 from "./ru/countries/italy.json";
import f560 from "./ru/countries/kazakhstan.json";
import f561 from "./ru/countries/mexico.json";
import f562 from "./ru/countries/netherlands.json";
import f563 from "./ru/countries/philippines.json";
import f564 from "./ru/countries/poland.json";
import f565 from "./ru/countries/portugal.json";
import f566 from "./ru/countries/spain.json";
import f567 from "./ru/countries/thailand.json";
import f568 from "./ru/countries/turkey.json";
import f569 from "./ru/countries/ukraine.json";
import f570 from "./ru/countries/united-kingdom.json";
import f571 from "./ru/countries/united-states.json";
import f572 from "./ru/countries/vietnam.json";
import f573 from "./ru/help/account-balance.json";
import f574 from "./ru/help/activation-issues.json";
import f575 from "./ru/help/billing-coins-refunds.json";
import f576 from "./ru/help/choosing-country.json";
import f577 from "./ru/home.json";
import f578 from "./ru/privacy.json";
import f579 from "./ru/services/adidas.json";
import f580 from "./ru/services/airbnb.json";
import f581 from "./ru/services/aliexpress.json";
import f582 from "./ru/services/apple.json";
import f583 from "./ru/services/binance.json";
import f584 from "./ru/services/cursor.json";
import f585 from "./ru/services/discord.json";
import f586 from "./ru/services/ebay.json";
import f587 from "./ru/services/facebook.json";
import f588 from "./ru/services/fiverr.json";
import f589 from "./ru/services/google.json";
import f590 from "./ru/services/grab.json";
import f591 from "./ru/services/instagram.json";
import f592 from "./ru/services/kakaotalk.json";
import f593 from "./ru/services/line.json";
import f594 from "./ru/services/netflix.json";
import f595 from "./ru/services/paypal.json";
import f596 from "./ru/services/reddit.json";
import f597 from "./ru/services/shopee.json";
import f598 from "./ru/services/signal.json";
import f599 from "./ru/services/snapchat.json";
import f600 from "./ru/services/steam.json";
import f601 from "./ru/services/telegram.json";
import f602 from "./ru/services/tiktok.json";
import f603 from "./ru/services/tinder.json";
import f604 from "./ru/services/twitch.json";
import f605 from "./ru/services/twitter.json";
import f606 from "./ru/services/uber.json";
import f607 from "./ru/services/viber.json";
import f608 from "./ru/services/vkcom.json";
import f609 from "./ru/services/wechat.json";
import f610 from "./ru/services/whatsapp.json";
import f611 from "./ru/services/zalo.json";
import f612 from "./ru/services-ui.json";
import f613 from "./ru/support.json";
import f614 from "./ru/terms.json";
import f615 from "./ru/ui.json";
import f616 from "./tr/alternatives/5sim.json";
import f617 from "./tr/alternatives/onlinesim.json";
import f618 from "./tr/alternatives/sms-activate-org.json";
import f619 from "./tr/alternatives/sms-man.json";
import f620 from "./tr/alternatives/textverified.json";
import f621 from "./tr/alternatives-ui.json";
import f622 from "./tr/blog/esim-vs-virtual-number.json";
import f623 from "./tr/blog/google-account-without-phone-number.json";
import f624 from "./tr/blog/how-to-receive-sms-online.json";
import f625 from "./tr/blog/second-whatsapp-account.json";
import f626 from "./tr/blog/telegram-without-phone-number.json";
import f627 from "./tr/blog/virtual-number-for-dating-apps.json";
import f628 from "./tr/blog/what-is-a-virtual-phone-number.json";
import f629 from "./tr/blog-ui.json";
import f630 from "./tr/countries/brazil.json";
import f631 from "./tr/countries/canada.json";
import f632 from "./tr/countries/france.json";
import f633 from "./tr/countries/germany.json";
import f634 from "./tr/countries/india.json";
import f635 from "./tr/countries/indonesia.json";
import f636 from "./tr/countries/italy.json";
import f637 from "./tr/countries/kazakhstan.json";
import f638 from "./tr/countries/mexico.json";
import f639 from "./tr/countries/netherlands.json";
import f640 from "./tr/countries/philippines.json";
import f641 from "./tr/countries/poland.json";
import f642 from "./tr/countries/portugal.json";
import f643 from "./tr/countries/spain.json";
import f644 from "./tr/countries/thailand.json";
import f645 from "./tr/countries/turkey.json";
import f646 from "./tr/countries/ukraine.json";
import f647 from "./tr/countries/united-kingdom.json";
import f648 from "./tr/countries/united-states.json";
import f649 from "./tr/countries/vietnam.json";
import f650 from "./tr/help/account-balance.json";
import f651 from "./tr/help/activation-issues.json";
import f652 from "./tr/help/billing-coins-refunds.json";
import f653 from "./tr/help/choosing-country.json";
import f654 from "./tr/home.json";
import f655 from "./tr/privacy.json";
import f656 from "./tr/services/adidas.json";
import f657 from "./tr/services/airbnb.json";
import f658 from "./tr/services/aliexpress.json";
import f659 from "./tr/services/apple.json";
import f660 from "./tr/services/binance.json";
import f661 from "./tr/services/cursor.json";
import f662 from "./tr/services/discord.json";
import f663 from "./tr/services/ebay.json";
import f664 from "./tr/services/facebook.json";
import f665 from "./tr/services/fiverr.json";
import f666 from "./tr/services/google.json";
import f667 from "./tr/services/grab.json";
import f668 from "./tr/services/instagram.json";
import f669 from "./tr/services/kakaotalk.json";
import f670 from "./tr/services/line.json";
import f671 from "./tr/services/netflix.json";
import f672 from "./tr/services/paypal.json";
import f673 from "./tr/services/reddit.json";
import f674 from "./tr/services/shopee.json";
import f675 from "./tr/services/signal.json";
import f676 from "./tr/services/snapchat.json";
import f677 from "./tr/services/steam.json";
import f678 from "./tr/services/telegram.json";
import f679 from "./tr/services/tiktok.json";
import f680 from "./tr/services/tinder.json";
import f681 from "./tr/services/twitch.json";
import f682 from "./tr/services/twitter.json";
import f683 from "./tr/services/uber.json";
import f684 from "./tr/services/viber.json";
import f685 from "./tr/services/vkcom.json";
import f686 from "./tr/services/wechat.json";
import f687 from "./tr/services/whatsapp.json";
import f688 from "./tr/services/zalo.json";
import f689 from "./tr/services-ui.json";
import f690 from "./tr/support.json";
import f691 from "./tr/terms.json";
import f692 from "./tr/ui.json";
import f693 from "./zh/alternatives/5sim.json";
import f694 from "./zh/alternatives/onlinesim.json";
import f695 from "./zh/alternatives/sms-activate-org.json";
import f696 from "./zh/alternatives/sms-man.json";
import f697 from "./zh/alternatives/textverified.json";
import f698 from "./zh/alternatives-ui.json";
import f699 from "./zh/blog/esim-vs-virtual-number.json";
import f700 from "./zh/blog/google-account-without-phone-number.json";
import f701 from "./zh/blog/how-to-receive-sms-online.json";
import f702 from "./zh/blog/second-whatsapp-account.json";
import f703 from "./zh/blog/telegram-without-phone-number.json";
import f704 from "./zh/blog/virtual-number-for-dating-apps.json";
import f705 from "./zh/blog/what-is-a-virtual-phone-number.json";
import f706 from "./zh/blog-ui.json";
import f707 from "./zh/countries/brazil.json";
import f708 from "./zh/countries/canada.json";
import f709 from "./zh/countries/france.json";
import f710 from "./zh/countries/germany.json";
import f711 from "./zh/countries/india.json";
import f712 from "./zh/countries/indonesia.json";
import f713 from "./zh/countries/italy.json";
import f714 from "./zh/countries/kazakhstan.json";
import f715 from "./zh/countries/mexico.json";
import f716 from "./zh/countries/netherlands.json";
import f717 from "./zh/countries/philippines.json";
import f718 from "./zh/countries/poland.json";
import f719 from "./zh/countries/portugal.json";
import f720 from "./zh/countries/spain.json";
import f721 from "./zh/countries/thailand.json";
import f722 from "./zh/countries/turkey.json";
import f723 from "./zh/countries/ukraine.json";
import f724 from "./zh/countries/united-kingdom.json";
import f725 from "./zh/countries/united-states.json";
import f726 from "./zh/countries/vietnam.json";
import f727 from "./zh/help/account-balance.json";
import f728 from "./zh/help/activation-issues.json";
import f729 from "./zh/help/billing-coins-refunds.json";
import f730 from "./zh/help/choosing-country.json";
import f731 from "./zh/home.json";
import f732 from "./zh/privacy.json";
import f733 from "./zh/services/adidas.json";
import f734 from "./zh/services/airbnb.json";
import f735 from "./zh/services/aliexpress.json";
import f736 from "./zh/services/apple.json";
import f737 from "./zh/services/binance.json";
import f738 from "./zh/services/cursor.json";
import f739 from "./zh/services/discord.json";
import f740 from "./zh/services/ebay.json";
import f741 from "./zh/services/facebook.json";
import f742 from "./zh/services/fiverr.json";
import f743 from "./zh/services/google.json";
import f744 from "./zh/services/grab.json";
import f745 from "./zh/services/instagram.json";
import f746 from "./zh/services/kakaotalk.json";
import f747 from "./zh/services/line.json";
import f748 from "./zh/services/netflix.json";
import f749 from "./zh/services/paypal.json";
import f750 from "./zh/services/reddit.json";
import f751 from "./zh/services/shopee.json";
import f752 from "./zh/services/signal.json";
import f753 from "./zh/services/snapchat.json";
import f754 from "./zh/services/steam.json";
import f755 from "./zh/services/telegram.json";
import f756 from "./zh/services/tiktok.json";
import f757 from "./zh/services/tinder.json";
import f758 from "./zh/services/twitch.json";
import f759 from "./zh/services/twitter.json";
import f760 from "./zh/services/uber.json";
import f761 from "./zh/services/viber.json";
import f762 from "./zh/services/vkcom.json";
import f763 from "./zh/services/wechat.json";
import f764 from "./zh/services/whatsapp.json";
import f765 from "./zh/services/zalo.json";
import f766 from "./zh/services-ui.json";
import f767 from "./zh/support.json";
import f768 from "./zh/terms.json";
import f769 from "./zh/ui.json";

export const LOCALE_FILES: Record<string, Record<string, unknown>> = {
  "ar": {
    "alternatives/5sim": f0,
    "alternatives/onlinesim": f1,
    "alternatives/sms-activate-org": f2,
    "alternatives/sms-man": f3,
    "alternatives/textverified": f4,
    "alternatives-ui": f5,
    "blog/esim-vs-virtual-number": f6,
    "blog/google-account-without-phone-number": f7,
    "blog/how-to-receive-sms-online": f8,
    "blog/second-whatsapp-account": f9,
    "blog/telegram-without-phone-number": f10,
    "blog/virtual-number-for-dating-apps": f11,
    "blog/what-is-a-virtual-phone-number": f12,
    "blog-ui": f13,
    "countries/brazil": f14,
    "countries/canada": f15,
    "countries/france": f16,
    "countries/germany": f17,
    "countries/india": f18,
    "countries/indonesia": f19,
    "countries/italy": f20,
    "countries/kazakhstan": f21,
    "countries/mexico": f22,
    "countries/netherlands": f23,
    "countries/philippines": f24,
    "countries/poland": f25,
    "countries/portugal": f26,
    "countries/spain": f27,
    "countries/thailand": f28,
    "countries/turkey": f29,
    "countries/ukraine": f30,
    "countries/united-kingdom": f31,
    "countries/united-states": f32,
    "countries/vietnam": f33,
    "help/account-balance": f34,
    "help/activation-issues": f35,
    "help/billing-coins-refunds": f36,
    "help/choosing-country": f37,
    "home": f38,
    "privacy": f39,
    "services/adidas": f40,
    "services/airbnb": f41,
    "services/aliexpress": f42,
    "services/apple": f43,
    "services/binance": f44,
    "services/cursor": f45,
    "services/discord": f46,
    "services/ebay": f47,
    "services/facebook": f48,
    "services/fiverr": f49,
    "services/google": f50,
    "services/grab": f51,
    "services/instagram": f52,
    "services/kakaotalk": f53,
    "services/line": f54,
    "services/netflix": f55,
    "services/paypal": f56,
    "services/reddit": f57,
    "services/shopee": f58,
    "services/signal": f59,
    "services/snapchat": f60,
    "services/steam": f61,
    "services/telegram": f62,
    "services/tiktok": f63,
    "services/tinder": f64,
    "services/twitch": f65,
    "services/twitter": f66,
    "services/uber": f67,
    "services/viber": f68,
    "services/vkcom": f69,
    "services/wechat": f70,
    "services/whatsapp": f71,
    "services/zalo": f72,
    "services-ui": f73,
    "support": f74,
    "terms": f75,
    "ui": f76,
  },
  "en": {
    "alternatives/5sim": f77,
    "alternatives/onlinesim": f78,
    "alternatives/sms-activate-org": f79,
    "alternatives/sms-man": f80,
    "alternatives/textverified": f81,
    "alternatives-ui": f82,
    "blog/esim-vs-virtual-number": f83,
    "blog/google-account-without-phone-number": f84,
    "blog/how-to-receive-sms-online": f85,
    "blog/second-whatsapp-account": f86,
    "blog/telegram-without-phone-number": f87,
    "blog/virtual-number-for-dating-apps": f88,
    "blog/what-is-a-virtual-phone-number": f89,
    "blog-ui": f90,
    "countries/brazil": f91,
    "countries/canada": f92,
    "countries/france": f93,
    "countries/germany": f94,
    "countries/india": f95,
    "countries/indonesia": f96,
    "countries/italy": f97,
    "countries/kazakhstan": f98,
    "countries/mexico": f99,
    "countries/netherlands": f100,
    "countries/philippines": f101,
    "countries/poland": f102,
    "countries/portugal": f103,
    "countries/spain": f104,
    "countries/thailand": f105,
    "countries/turkey": f106,
    "countries/ukraine": f107,
    "countries/united-kingdom": f108,
    "countries/united-states": f109,
    "countries/vietnam": f110,
    "help/account-balance": f111,
    "help/activation-issues": f112,
    "help/billing-coins-refunds": f113,
    "help/choosing-country": f114,
    "home": f115,
    "privacy": f116,
    "services/adidas": f117,
    "services/airbnb": f118,
    "services/aliexpress": f119,
    "services/apple": f120,
    "services/binance": f121,
    "services/cursor": f122,
    "services/discord": f123,
    "services/ebay": f124,
    "services/facebook": f125,
    "services/fiverr": f126,
    "services/google": f127,
    "services/grab": f128,
    "services/instagram": f129,
    "services/kakaotalk": f130,
    "services/line": f131,
    "services/netflix": f132,
    "services/paypal": f133,
    "services/reddit": f134,
    "services/shopee": f135,
    "services/signal": f136,
    "services/snapchat": f137,
    "services/steam": f138,
    "services/telegram": f139,
    "services/tiktok": f140,
    "services/tinder": f141,
    "services/twitch": f142,
    "services/twitter": f143,
    "services/uber": f144,
    "services/viber": f145,
    "services/vkcom": f146,
    "services/wechat": f147,
    "services/whatsapp": f148,
    "services/zalo": f149,
    "services-ui": f150,
    "support": f151,
    "terms": f152,
    "ui": f153,
  },
  "es": {
    "alternatives/5sim": f154,
    "alternatives/onlinesim": f155,
    "alternatives/sms-activate-org": f156,
    "alternatives/sms-man": f157,
    "alternatives/textverified": f158,
    "alternatives-ui": f159,
    "blog/esim-vs-virtual-number": f160,
    "blog/google-account-without-phone-number": f161,
    "blog/how-to-receive-sms-online": f162,
    "blog/second-whatsapp-account": f163,
    "blog/telegram-without-phone-number": f164,
    "blog/virtual-number-for-dating-apps": f165,
    "blog/what-is-a-virtual-phone-number": f166,
    "blog-ui": f167,
    "countries/brazil": f168,
    "countries/canada": f169,
    "countries/france": f170,
    "countries/germany": f171,
    "countries/india": f172,
    "countries/indonesia": f173,
    "countries/italy": f174,
    "countries/kazakhstan": f175,
    "countries/mexico": f176,
    "countries/netherlands": f177,
    "countries/philippines": f178,
    "countries/poland": f179,
    "countries/portugal": f180,
    "countries/spain": f181,
    "countries/thailand": f182,
    "countries/turkey": f183,
    "countries/ukraine": f184,
    "countries/united-kingdom": f185,
    "countries/united-states": f186,
    "countries/vietnam": f187,
    "help/account-balance": f188,
    "help/activation-issues": f189,
    "help/billing-coins-refunds": f190,
    "help/choosing-country": f191,
    "home": f192,
    "privacy": f193,
    "services/adidas": f194,
    "services/airbnb": f195,
    "services/aliexpress": f196,
    "services/apple": f197,
    "services/binance": f198,
    "services/cursor": f199,
    "services/discord": f200,
    "services/ebay": f201,
    "services/facebook": f202,
    "services/fiverr": f203,
    "services/google": f204,
    "services/grab": f205,
    "services/instagram": f206,
    "services/kakaotalk": f207,
    "services/line": f208,
    "services/netflix": f209,
    "services/paypal": f210,
    "services/reddit": f211,
    "services/shopee": f212,
    "services/signal": f213,
    "services/snapchat": f214,
    "services/steam": f215,
    "services/telegram": f216,
    "services/tiktok": f217,
    "services/tinder": f218,
    "services/twitch": f219,
    "services/twitter": f220,
    "services/uber": f221,
    "services/viber": f222,
    "services/vkcom": f223,
    "services/wechat": f224,
    "services/whatsapp": f225,
    "services/zalo": f226,
    "services-ui": f227,
    "support": f228,
    "terms": f229,
    "ui": f230,
  },
  "fr": {
    "alternatives/5sim": f231,
    "alternatives/onlinesim": f232,
    "alternatives/sms-activate-org": f233,
    "alternatives/sms-man": f234,
    "alternatives/textverified": f235,
    "alternatives-ui": f236,
    "blog/esim-vs-virtual-number": f237,
    "blog/google-account-without-phone-number": f238,
    "blog/how-to-receive-sms-online": f239,
    "blog/second-whatsapp-account": f240,
    "blog/telegram-without-phone-number": f241,
    "blog/virtual-number-for-dating-apps": f242,
    "blog/what-is-a-virtual-phone-number": f243,
    "blog-ui": f244,
    "countries/brazil": f245,
    "countries/canada": f246,
    "countries/france": f247,
    "countries/germany": f248,
    "countries/india": f249,
    "countries/indonesia": f250,
    "countries/italy": f251,
    "countries/kazakhstan": f252,
    "countries/mexico": f253,
    "countries/netherlands": f254,
    "countries/philippines": f255,
    "countries/poland": f256,
    "countries/portugal": f257,
    "countries/spain": f258,
    "countries/thailand": f259,
    "countries/turkey": f260,
    "countries/ukraine": f261,
    "countries/united-kingdom": f262,
    "countries/united-states": f263,
    "countries/vietnam": f264,
    "help/account-balance": f265,
    "help/activation-issues": f266,
    "help/billing-coins-refunds": f267,
    "help/choosing-country": f268,
    "home": f269,
    "privacy": f270,
    "services/adidas": f271,
    "services/airbnb": f272,
    "services/aliexpress": f273,
    "services/apple": f274,
    "services/binance": f275,
    "services/cursor": f276,
    "services/discord": f277,
    "services/ebay": f278,
    "services/facebook": f279,
    "services/fiverr": f280,
    "services/google": f281,
    "services/grab": f282,
    "services/instagram": f283,
    "services/kakaotalk": f284,
    "services/line": f285,
    "services/netflix": f286,
    "services/paypal": f287,
    "services/reddit": f288,
    "services/shopee": f289,
    "services/signal": f290,
    "services/snapchat": f291,
    "services/steam": f292,
    "services/telegram": f293,
    "services/tiktok": f294,
    "services/tinder": f295,
    "services/twitch": f296,
    "services/twitter": f297,
    "services/uber": f298,
    "services/viber": f299,
    "services/vkcom": f300,
    "services/wechat": f301,
    "services/whatsapp": f302,
    "services/zalo": f303,
    "services-ui": f304,
    "support": f305,
    "terms": f306,
    "ui": f307,
  },
  "hi": {
    "alternatives/5sim": f308,
    "alternatives/onlinesim": f309,
    "alternatives/sms-activate-org": f310,
    "alternatives/sms-man": f311,
    "alternatives/textverified": f312,
    "alternatives-ui": f313,
    "blog/esim-vs-virtual-number": f314,
    "blog/google-account-without-phone-number": f315,
    "blog/how-to-receive-sms-online": f316,
    "blog/second-whatsapp-account": f317,
    "blog/telegram-without-phone-number": f318,
    "blog/virtual-number-for-dating-apps": f319,
    "blog/what-is-a-virtual-phone-number": f320,
    "blog-ui": f321,
    "countries/brazil": f322,
    "countries/canada": f323,
    "countries/france": f324,
    "countries/germany": f325,
    "countries/india": f326,
    "countries/indonesia": f327,
    "countries/italy": f328,
    "countries/kazakhstan": f329,
    "countries/mexico": f330,
    "countries/netherlands": f331,
    "countries/philippines": f332,
    "countries/poland": f333,
    "countries/portugal": f334,
    "countries/spain": f335,
    "countries/thailand": f336,
    "countries/turkey": f337,
    "countries/ukraine": f338,
    "countries/united-kingdom": f339,
    "countries/united-states": f340,
    "countries/vietnam": f341,
    "help/account-balance": f342,
    "help/activation-issues": f343,
    "help/billing-coins-refunds": f344,
    "help/choosing-country": f345,
    "home": f346,
    "privacy": f347,
    "services/adidas": f348,
    "services/airbnb": f349,
    "services/aliexpress": f350,
    "services/apple": f351,
    "services/binance": f352,
    "services/cursor": f353,
    "services/discord": f354,
    "services/ebay": f355,
    "services/facebook": f356,
    "services/fiverr": f357,
    "services/google": f358,
    "services/grab": f359,
    "services/instagram": f360,
    "services/kakaotalk": f361,
    "services/line": f362,
    "services/netflix": f363,
    "services/paypal": f364,
    "services/reddit": f365,
    "services/shopee": f366,
    "services/signal": f367,
    "services/snapchat": f368,
    "services/steam": f369,
    "services/telegram": f370,
    "services/tiktok": f371,
    "services/tinder": f372,
    "services/twitch": f373,
    "services/twitter": f374,
    "services/uber": f375,
    "services/viber": f376,
    "services/vkcom": f377,
    "services/wechat": f378,
    "services/whatsapp": f379,
    "services/zalo": f380,
    "services-ui": f381,
    "support": f382,
    "terms": f383,
    "ui": f384,
  },
  "id": {
    "alternatives/5sim": f385,
    "alternatives/onlinesim": f386,
    "alternatives/sms-activate-org": f387,
    "alternatives/sms-man": f388,
    "alternatives/textverified": f389,
    "alternatives-ui": f390,
    "blog/esim-vs-virtual-number": f391,
    "blog/google-account-without-phone-number": f392,
    "blog/how-to-receive-sms-online": f393,
    "blog/second-whatsapp-account": f394,
    "blog/telegram-without-phone-number": f395,
    "blog/virtual-number-for-dating-apps": f396,
    "blog/what-is-a-virtual-phone-number": f397,
    "blog-ui": f398,
    "countries/brazil": f399,
    "countries/canada": f400,
    "countries/france": f401,
    "countries/germany": f402,
    "countries/india": f403,
    "countries/indonesia": f404,
    "countries/italy": f405,
    "countries/kazakhstan": f406,
    "countries/mexico": f407,
    "countries/netherlands": f408,
    "countries/philippines": f409,
    "countries/poland": f410,
    "countries/portugal": f411,
    "countries/spain": f412,
    "countries/thailand": f413,
    "countries/turkey": f414,
    "countries/ukraine": f415,
    "countries/united-kingdom": f416,
    "countries/united-states": f417,
    "countries/vietnam": f418,
    "help/account-balance": f419,
    "help/activation-issues": f420,
    "help/billing-coins-refunds": f421,
    "help/choosing-country": f422,
    "home": f423,
    "privacy": f424,
    "services/adidas": f425,
    "services/airbnb": f426,
    "services/aliexpress": f427,
    "services/apple": f428,
    "services/binance": f429,
    "services/cursor": f430,
    "services/discord": f431,
    "services/ebay": f432,
    "services/facebook": f433,
    "services/fiverr": f434,
    "services/google": f435,
    "services/grab": f436,
    "services/instagram": f437,
    "services/kakaotalk": f438,
    "services/line": f439,
    "services/netflix": f440,
    "services/paypal": f441,
    "services/reddit": f442,
    "services/shopee": f443,
    "services/signal": f444,
    "services/snapchat": f445,
    "services/steam": f446,
    "services/telegram": f447,
    "services/tiktok": f448,
    "services/tinder": f449,
    "services/twitch": f450,
    "services/twitter": f451,
    "services/uber": f452,
    "services/viber": f453,
    "services/vkcom": f454,
    "services/wechat": f455,
    "services/whatsapp": f456,
    "services/zalo": f457,
    "services-ui": f458,
    "support": f459,
    "terms": f460,
    "ui": f461,
  },
  "pt": {
    "alternatives/5sim": f462,
    "alternatives/onlinesim": f463,
    "alternatives/sms-activate-org": f464,
    "alternatives/sms-man": f465,
    "alternatives/textverified": f466,
    "alternatives-ui": f467,
    "blog/esim-vs-virtual-number": f468,
    "blog/google-account-without-phone-number": f469,
    "blog/how-to-receive-sms-online": f470,
    "blog/second-whatsapp-account": f471,
    "blog/telegram-without-phone-number": f472,
    "blog/virtual-number-for-dating-apps": f473,
    "blog/what-is-a-virtual-phone-number": f474,
    "blog-ui": f475,
    "countries/brazil": f476,
    "countries/canada": f477,
    "countries/france": f478,
    "countries/germany": f479,
    "countries/india": f480,
    "countries/indonesia": f481,
    "countries/italy": f482,
    "countries/kazakhstan": f483,
    "countries/mexico": f484,
    "countries/netherlands": f485,
    "countries/philippines": f486,
    "countries/poland": f487,
    "countries/portugal": f488,
    "countries/spain": f489,
    "countries/thailand": f490,
    "countries/turkey": f491,
    "countries/ukraine": f492,
    "countries/united-kingdom": f493,
    "countries/united-states": f494,
    "countries/vietnam": f495,
    "help/account-balance": f496,
    "help/activation-issues": f497,
    "help/billing-coins-refunds": f498,
    "help/choosing-country": f499,
    "home": f500,
    "privacy": f501,
    "services/adidas": f502,
    "services/airbnb": f503,
    "services/aliexpress": f504,
    "services/apple": f505,
    "services/binance": f506,
    "services/cursor": f507,
    "services/discord": f508,
    "services/ebay": f509,
    "services/facebook": f510,
    "services/fiverr": f511,
    "services/google": f512,
    "services/grab": f513,
    "services/instagram": f514,
    "services/kakaotalk": f515,
    "services/line": f516,
    "services/netflix": f517,
    "services/paypal": f518,
    "services/reddit": f519,
    "services/shopee": f520,
    "services/signal": f521,
    "services/snapchat": f522,
    "services/steam": f523,
    "services/telegram": f524,
    "services/tiktok": f525,
    "services/tinder": f526,
    "services/twitch": f527,
    "services/twitter": f528,
    "services/uber": f529,
    "services/viber": f530,
    "services/vkcom": f531,
    "services/wechat": f532,
    "services/whatsapp": f533,
    "services/zalo": f534,
    "services-ui": f535,
    "support": f536,
    "terms": f537,
    "ui": f538,
  },
  "ru": {
    "alternatives/5sim": f539,
    "alternatives/onlinesim": f540,
    "alternatives/sms-activate-org": f541,
    "alternatives/sms-man": f542,
    "alternatives/textverified": f543,
    "alternatives-ui": f544,
    "blog/esim-vs-virtual-number": f545,
    "blog/google-account-without-phone-number": f546,
    "blog/how-to-receive-sms-online": f547,
    "blog/second-whatsapp-account": f548,
    "blog/telegram-without-phone-number": f549,
    "blog/virtual-number-for-dating-apps": f550,
    "blog/what-is-a-virtual-phone-number": f551,
    "blog-ui": f552,
    "countries/brazil": f553,
    "countries/canada": f554,
    "countries/france": f555,
    "countries/germany": f556,
    "countries/india": f557,
    "countries/indonesia": f558,
    "countries/italy": f559,
    "countries/kazakhstan": f560,
    "countries/mexico": f561,
    "countries/netherlands": f562,
    "countries/philippines": f563,
    "countries/poland": f564,
    "countries/portugal": f565,
    "countries/spain": f566,
    "countries/thailand": f567,
    "countries/turkey": f568,
    "countries/ukraine": f569,
    "countries/united-kingdom": f570,
    "countries/united-states": f571,
    "countries/vietnam": f572,
    "help/account-balance": f573,
    "help/activation-issues": f574,
    "help/billing-coins-refunds": f575,
    "help/choosing-country": f576,
    "home": f577,
    "privacy": f578,
    "services/adidas": f579,
    "services/airbnb": f580,
    "services/aliexpress": f581,
    "services/apple": f582,
    "services/binance": f583,
    "services/cursor": f584,
    "services/discord": f585,
    "services/ebay": f586,
    "services/facebook": f587,
    "services/fiverr": f588,
    "services/google": f589,
    "services/grab": f590,
    "services/instagram": f591,
    "services/kakaotalk": f592,
    "services/line": f593,
    "services/netflix": f594,
    "services/paypal": f595,
    "services/reddit": f596,
    "services/shopee": f597,
    "services/signal": f598,
    "services/snapchat": f599,
    "services/steam": f600,
    "services/telegram": f601,
    "services/tiktok": f602,
    "services/tinder": f603,
    "services/twitch": f604,
    "services/twitter": f605,
    "services/uber": f606,
    "services/viber": f607,
    "services/vkcom": f608,
    "services/wechat": f609,
    "services/whatsapp": f610,
    "services/zalo": f611,
    "services-ui": f612,
    "support": f613,
    "terms": f614,
    "ui": f615,
  },
  "tr": {
    "alternatives/5sim": f616,
    "alternatives/onlinesim": f617,
    "alternatives/sms-activate-org": f618,
    "alternatives/sms-man": f619,
    "alternatives/textverified": f620,
    "alternatives-ui": f621,
    "blog/esim-vs-virtual-number": f622,
    "blog/google-account-without-phone-number": f623,
    "blog/how-to-receive-sms-online": f624,
    "blog/second-whatsapp-account": f625,
    "blog/telegram-without-phone-number": f626,
    "blog/virtual-number-for-dating-apps": f627,
    "blog/what-is-a-virtual-phone-number": f628,
    "blog-ui": f629,
    "countries/brazil": f630,
    "countries/canada": f631,
    "countries/france": f632,
    "countries/germany": f633,
    "countries/india": f634,
    "countries/indonesia": f635,
    "countries/italy": f636,
    "countries/kazakhstan": f637,
    "countries/mexico": f638,
    "countries/netherlands": f639,
    "countries/philippines": f640,
    "countries/poland": f641,
    "countries/portugal": f642,
    "countries/spain": f643,
    "countries/thailand": f644,
    "countries/turkey": f645,
    "countries/ukraine": f646,
    "countries/united-kingdom": f647,
    "countries/united-states": f648,
    "countries/vietnam": f649,
    "help/account-balance": f650,
    "help/activation-issues": f651,
    "help/billing-coins-refunds": f652,
    "help/choosing-country": f653,
    "home": f654,
    "privacy": f655,
    "services/adidas": f656,
    "services/airbnb": f657,
    "services/aliexpress": f658,
    "services/apple": f659,
    "services/binance": f660,
    "services/cursor": f661,
    "services/discord": f662,
    "services/ebay": f663,
    "services/facebook": f664,
    "services/fiverr": f665,
    "services/google": f666,
    "services/grab": f667,
    "services/instagram": f668,
    "services/kakaotalk": f669,
    "services/line": f670,
    "services/netflix": f671,
    "services/paypal": f672,
    "services/reddit": f673,
    "services/shopee": f674,
    "services/signal": f675,
    "services/snapchat": f676,
    "services/steam": f677,
    "services/telegram": f678,
    "services/tiktok": f679,
    "services/tinder": f680,
    "services/twitch": f681,
    "services/twitter": f682,
    "services/uber": f683,
    "services/viber": f684,
    "services/vkcom": f685,
    "services/wechat": f686,
    "services/whatsapp": f687,
    "services/zalo": f688,
    "services-ui": f689,
    "support": f690,
    "terms": f691,
    "ui": f692,
  },
  "zh": {
    "alternatives/5sim": f693,
    "alternatives/onlinesim": f694,
    "alternatives/sms-activate-org": f695,
    "alternatives/sms-man": f696,
    "alternatives/textverified": f697,
    "alternatives-ui": f698,
    "blog/esim-vs-virtual-number": f699,
    "blog/google-account-without-phone-number": f700,
    "blog/how-to-receive-sms-online": f701,
    "blog/second-whatsapp-account": f702,
    "blog/telegram-without-phone-number": f703,
    "blog/virtual-number-for-dating-apps": f704,
    "blog/what-is-a-virtual-phone-number": f705,
    "blog-ui": f706,
    "countries/brazil": f707,
    "countries/canada": f708,
    "countries/france": f709,
    "countries/germany": f710,
    "countries/india": f711,
    "countries/indonesia": f712,
    "countries/italy": f713,
    "countries/kazakhstan": f714,
    "countries/mexico": f715,
    "countries/netherlands": f716,
    "countries/philippines": f717,
    "countries/poland": f718,
    "countries/portugal": f719,
    "countries/spain": f720,
    "countries/thailand": f721,
    "countries/turkey": f722,
    "countries/ukraine": f723,
    "countries/united-kingdom": f724,
    "countries/united-states": f725,
    "countries/vietnam": f726,
    "help/account-balance": f727,
    "help/activation-issues": f728,
    "help/billing-coins-refunds": f729,
    "help/choosing-country": f730,
    "home": f731,
    "privacy": f732,
    "services/adidas": f733,
    "services/airbnb": f734,
    "services/aliexpress": f735,
    "services/apple": f736,
    "services/binance": f737,
    "services/cursor": f738,
    "services/discord": f739,
    "services/ebay": f740,
    "services/facebook": f741,
    "services/fiverr": f742,
    "services/google": f743,
    "services/grab": f744,
    "services/instagram": f745,
    "services/kakaotalk": f746,
    "services/line": f747,
    "services/netflix": f748,
    "services/paypal": f749,
    "services/reddit": f750,
    "services/shopee": f751,
    "services/signal": f752,
    "services/snapchat": f753,
    "services/steam": f754,
    "services/telegram": f755,
    "services/tiktok": f756,
    "services/tinder": f757,
    "services/twitch": f758,
    "services/twitter": f759,
    "services/uber": f760,
    "services/viber": f761,
    "services/vkcom": f762,
    "services/wechat": f763,
    "services/whatsapp": f764,
    "services/zalo": f765,
    "services-ui": f766,
    "support": f767,
    "terms": f768,
    "ui": f769,
  },
};
