import type { CountryMeta } from "./types";

export const COUNTRIES_META: CountryMeta[] = [
  {
    slug: "united-states",
    flag: "🇺🇸",
    dialingCode: "+1",
    numberFormat: "+1 (XXX) XXX-XXXX",
    popularServiceSlugs: ["google", "instagram", "tiktok", "discord", "tinder"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "united-kingdom",
    flag: "🇬🇧",
    dialingCode: "+44",
    numberFormat: "+44 7XXX XXXXXX",
    popularServiceSlugs: ["whatsapp", "google", "telegram", "airbnb", "paypal"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "germany",
    flag: "🇩🇪",
    dialingCode: "+49",
    numberFormat: "+49 15X XXXXXXXX",
    popularServiceSlugs: ["google", "discord", "steam", "signal", "paypal"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "france",
    flag: "🇫🇷",
    dialingCode: "+33",
    numberFormat: "+33 6 XX XX XX XX",
    popularServiceSlugs: ["instagram", "tinder", "uber", "airbnb", "google"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "poland",
    flag: "🇵🇱",
    dialingCode: "+48",
    numberFormat: "+48 XXX XXX XXX",
    popularServiceSlugs: ["telegram", "whatsapp", "steam", "aliexpress", "viber"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "ukraine",
    flag: "🇺🇦",
    dialingCode: "+380",
    numberFormat: "+380 XX XXX XX XX",
    popularServiceSlugs: ["telegram", "viber", "aliexpress", "vkcom", "google"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "kazakhstan",
    flag: "🇰🇿",
    dialingCode: "+7",
    numberFormat: "+7 7XX XXX XX XX",
    popularServiceSlugs: ["telegram", "vkcom", "viber", "steam", "whatsapp"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "netherlands",
    flag: "🇳🇱",
    dialingCode: "+31",
    numberFormat: "+31 6 XXXXXXXX",
    popularServiceSlugs: ["telegram", "whatsapp", "google", "discord", "signal"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "indonesia",
    flag: "🇮🇩",
    dialingCode: "+62",
    numberFormat: "+62 8XX XXXX XXXX",
    popularServiceSlugs: ["whatsapp", "telegram", "tiktok", "grab", "line"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "philippines",
    flag: "🇵🇭",
    dialingCode: "+63",
    numberFormat: "+63 9XX XXX XXXX",
    popularServiceSlugs: ["facebook", "viber", "grab", "tiktok", "whatsapp"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "india",
    flag: "🇮🇳",
    dialingCode: "+91",
    numberFormat: "+91 XXXXX XXXXX",
    popularServiceSlugs: ["whatsapp", "telegram", "google", "instagram", "uber"],
    updatedAt: "2026-09-30",
  },
  {
    slug: "brazil",
    flag: "🇧🇷",
    dialingCode: "+55",
    numberFormat: "+55 XX 9XXXX-XXXX",
    popularServiceSlugs: ["whatsapp", "instagram", "tiktok", "uber", "facebook"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "canada",
    flag: "🇨🇦",
    dialingCode: "+1",
    numberFormat: "+1 (XXX) XXX-XXXX",
    popularServiceSlugs: ["google", "discord", "tinder", "snapchat", "apple"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "spain",
    flag: "🇪🇸",
    dialingCode: "+34",
    numberFormat: "+34 6XX XXX XXX",
    popularServiceSlugs: ["whatsapp", "instagram", "tinder", "aliexpress", "airbnb"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "italy",
    flag: "🇮🇹",
    dialingCode: "+39",
    numberFormat: "+39 3XX XXX XXXX",
    popularServiceSlugs: ["whatsapp", "instagram", "telegram", "airbnb", "google"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "turkey",
    flag: "🇹🇷",
    dialingCode: "+90",
    numberFormat: "+90 5XX XXX XX XX",
    popularServiceSlugs: ["telegram", "whatsapp", "instagram", "tiktok", "binance"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "mexico",
    flag: "🇲🇽",
    dialingCode: "+52",
    numberFormat: "+52 XX XXXX XXXX",
    popularServiceSlugs: ["whatsapp", "telegram", "facebook", "uber", "tinder"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "vietnam",
    flag: "🇻🇳",
    dialingCode: "+84",
    numberFormat: "+84 XX XXX XX XX",
    popularServiceSlugs: ["zalo", "telegram", "whatsapp", "shopee", "facebook"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "thailand",
    flag: "🇹🇭",
    dialingCode: "+66",
    numberFormat: "+66 X XXXX XXXX",
    popularServiceSlugs: ["line", "shopee", "whatsapp", "telegram", "grab"],
    updatedAt: "2026-07-07",
  },
  {
    slug: "portugal",
    flag: "🇵🇹",
    dialingCode: "+351",
    numberFormat: "+351 9X XXX XXXX",
    popularServiceSlugs: ["whatsapp", "telegram", "instagram", "uber", "aliexpress"],
    updatedAt: "2026-07-07",
  },
];
