import type { ServiceMeta } from "./types";

export const SERVICES_META: ServiceMeta[] = [
  {
    slug: "telegram",
    name: "Telegram",
    logo: "/services/telegram.svg",
    category: "messaging",
    relatedSlugs: ["whatsapp", "signal", "viber", "discord", "google"],
    popularCountries: ["netherlands", "united-kingdom", "poland", "kazakhstan", "indonesia"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Telegram",
      message: "Telegram code: 48329",
      code: "48329",
    },
  },
  {
    slug: "whatsapp",
    name: "WhatsApp",
    logo: "/services/whatsapp.svg",
    category: "messaging",
    relatedSlugs: ["telegram", "viber", "signal", "facebook", "instagram"],
    popularCountries: ["united-kingdom", "poland", "netherlands", "indonesia", "philippines"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "WhatsApp",
      message: "WhatsApp code 305-921",
      code: "305-921",
    },
  },
  {
    slug: "google",
    name: "Google",
    logo: "/services/google.svg",
    category: "other",
    relatedSlugs: ["apple", "facebook", "twitter", "discord", "telegram"],
    popularCountries: ["united-states", "united-kingdom", "germany", "netherlands", "poland"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Google",
      message: "G-482915 is your Google verification code.",
      code: "G-482915",
    },
  },
  {
    slug: "instagram",
    name: "Instagram",
    logo: "/services/instagram.svg",
    category: "social",
    relatedSlugs: ["facebook", "tiktok", "snapchat", "twitter", "tinder"],
    popularCountries: ["united-states", "united-kingdom", "france", "spain", "brazil"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Instagram",
      message: "391 504 is your Instagram code. Don't share it.",
      code: "391 504",
    },
  },
  {
    slug: "tiktok",
    name: "TikTok",
    logo: "/services/tiktok.svg",
    category: "social",
    relatedSlugs: ["instagram", "snapchat", "twitter", "facebook", "discord"],
    popularCountries: ["united-states", "united-kingdom", "indonesia", "philippines", "brazil"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "TikTok",
      message: "[TikTok] 604812 is your verification code, valid for 5 minutes.",
      code: "604812",
    },
  },
  {
    slug: "discord",
    name: "Discord",
    logo: "/services/discord.svg",
    category: "messaging",
    relatedSlugs: ["telegram", "steam", "google", "twitter", "signal"],
    popularCountries: ["united-states", "united-kingdom", "germany", "canada", "netherlands"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Discord",
      message: "Your Discord verification code is: 274918",
      code: "274918",
    },
  },
  {
    slug: "facebook",
    name: "Facebook",
    logo: "/services/facebook.svg",
    category: "social",
    relatedSlugs: ["instagram", "twitter", "tiktok", "snapchat", "google"],
    popularCountries: ["united-states", "united-kingdom", "germany", "france", "brazil"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Facebook",
      message: "285103 is your Facebook confirmation code",
      code: "285103",
    },
  },
  {
    slug: "snapchat",
    name: "Snapchat",
    logo: "/services/snapchat.svg",
    category: "social",
    relatedSlugs: ["instagram", "tiktok", "tinder", "discord", "whatsapp"],
    popularCountries: ["united-states", "united-kingdom", "canada", "netherlands", "france"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Snapchat",
      message: "Snapchat code: 719402. Happy Snapping!",
      code: "719402",
    },
  },
  {
    slug: "tinder",
    name: "Tinder",
    logo: "/services/tinder.svg",
    category: "social",
    relatedSlugs: ["snapchat", "instagram", "whatsapp", "telegram", "facebook"],
    popularCountries: ["united-states", "united-kingdom", "spain", "france", "brazil"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Tinder",
      message: "Your Tinder code is 402318 dwEzWOx6XSV",
      code: "402318",
    },
  },
  {
    slug: "viber",
    name: "Viber",
    logo: "/services/viber.svg",
    category: "messaging",
    relatedSlugs: ["whatsapp", "telegram", "signal", "line", "wechat"],
    popularCountries: ["ukraine", "kazakhstan", "poland", "philippines", "germany"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Viber",
      message: "Your Viber code: 528114",
      code: "528114",
    },
  },
  {
    slug: "signal",
    name: "Signal",
    logo: "/services/signal.svg",
    category: "messaging",
    relatedSlugs: ["telegram", "whatsapp", "viber", "discord", "google"],
    popularCountries: ["united-states", "germany", "netherlands", "canada", "united-kingdom"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Signal",
      message: "SIGNAL: Your code is: 613904",
      code: "613904",
    },
  },
  {
    slug: "twitter",
    name: "X (Twitter)",
    logo: "/services/twitter.svg",
    category: "social",
    relatedSlugs: ["facebook", "instagram", "tiktok", "discord", "google"],
    popularCountries: ["united-states", "united-kingdom", "germany", "netherlands", "canada"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "X",
      message: "Your X confirmation code is 941507. Don't share this code with anyone.",
      code: "941507",
    },
  },
  {
    slug: "line",
    name: "LINE",
    logo: "/services/line.svg",
    category: "messaging",
    relatedSlugs: ["wechat", "viber", "whatsapp", "telegram", "grab"],
    popularCountries: ["indonesia", "philippines", "united-states", "united-kingdom", "canada"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "LINE",
      message: "Your verification code is 4820. Enter it in LINE within the next 30 mins.",
      code: "4820",
    },
  },
  {
    slug: "airbnb",
    name: "Airbnb",
    logo: "/services/airbnb.svg",
    category: "travel",
    relatedSlugs: ["uber", "grab", "paypal", "google", "apple"],
    popularCountries: ["united-states", "united-kingdom", "france", "spain", "italy"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Airbnb",
      message: "Your Airbnb verification code is: 517203.",
      code: "517203",
    },
  },
  {
    slug: "grab",
    name: "Grab",
    logo: "/services/grab.svg",
    category: "travel",
    relatedSlugs: ["uber", "line", "airbnb", "aliexpress", "google"],
    popularCountries: ["indonesia", "philippines", "united-states", "united-kingdom", "canada"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Grab",
      message: "702415 is your Grab activation code. For your account safety, do not share this code.",
      code: "702415",
    },
  },
  {
    slug: "vkcom",
    name: "VK",
    logo: "/services/vkcom.svg",
    category: "social",
    relatedSlugs: ["telegram", "viber", "facebook", "twitter", "google"],
    popularCountries: ["kazakhstan", "ukraine", "poland", "germany", "netherlands"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "VK",
      message: "VK: 348715 — код подтверждения",
      code: "348715",
    },
  },
  {
    slug: "adidas",
    name: "adidas",
    logo: "/services/adidas.svg",
    category: "shopping",
    relatedSlugs: ["aliexpress", "paypal", "uber", "google", "apple"],
    popularCountries: ["united-states", "united-kingdom", "germany", "france", "spain"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "adidas",
      message: "Your adidas verification code is 604927",
      code: "604927",
    },
  },
  {
    slug: "cursor",
    name: "Cursor",
    logo: "/services/cursor.svg",
    category: "dev",
    relatedSlugs: ["google", "discord", "apple", "telegram", "steam"],
    popularCountries: ["united-states", "germany", "united-kingdom", "netherlands", "canada"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Cursor",
      message: "Your Cursor verification code is 812750",
      code: "812750",
    },
  },
  {
    slug: "apple",
    name: "Apple",
    logo: "/services/apple.svg",
    category: "other",
    relatedSlugs: ["google", "netflix", "paypal", "steam", "facebook"],
    popularCountries: ["united-states", "united-kingdom", "germany", "canada", "netherlands"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Apple",
      message: "Your Apple Account code is: 617402. Don't share it with anyone.",
      code: "617402",
    },
  },
  {
    slug: "netflix",
    name: "Netflix",
    logo: "/services/netflix.svg",
    category: "entertainment",
    relatedSlugs: ["steam", "apple", "google", "paypal", "aliexpress"],
    popularCountries: ["united-states", "united-kingdom", "germany", "france", "poland"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Netflix",
      message: "Your Netflix verification code is 428916",
      code: "428916",
    },
  },
  {
    slug: "paypal",
    name: "PayPal",
    logo: "/services/paypal.svg",
    category: "finance",
    relatedSlugs: ["aliexpress", "uber", "apple", "google", "steam"],
    popularCountries: ["united-states", "united-kingdom", "germany", "france", "netherlands"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "PayPal",
      message: "Your PayPal security code is: 305174. It expires in 10 minutes.",
      code: "305174",
    },
  },
  {
    slug: "uber",
    name: "Uber",
    logo: "/services/uber.svg",
    category: "travel",
    relatedSlugs: ["grab", "airbnb", "aliexpress", "google", "paypal"],
    popularCountries: ["united-states", "united-kingdom", "france", "brazil", "india"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Uber",
      message: "Your Uber code is 7204. Never share this code.",
      code: "7204",
    },
  },
  {
    slug: "steam",
    name: "Steam",
    logo: "/services/steam.svg",
    category: "entertainment",
    relatedSlugs: ["discord", "netflix", "google", "apple", "twitter"],
    popularCountries: ["united-states", "germany", "poland", "kazakhstan", "brazil"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Steam",
      message: "Your Steam verification code is J4K8P",
      code: "J4K8P",
    },
  },
  {
    slug: "aliexpress",
    name: "AliExpress",
    logo: "/services/aliexpress.svg",
    category: "shopping",
    relatedSlugs: ["paypal", "uber", "adidas", "google", "wechat"],
    popularCountries: ["united-states", "spain", "poland", "brazil", "ukraine"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "AliExpress",
      message: "AliExpress verification code: 902731",
      code: "902731",
    },
  },
  {
    slug: "wechat",
    name: "WeChat",
    logo: "/services/wechat.svg",
    category: "messaging",
    relatedSlugs: ["line", "viber", "whatsapp", "telegram", "aliexpress"],
    popularCountries: ["united-states", "united-kingdom", "canada", "indonesia", "philippines"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "WeChat",
      message: "Use the code (582074) on WeChat to log in to your account.",
      code: "582074",
    },
  },
  {
    slug: "twitch",
    name: "Twitch",
    logo: "/services/twitch.svg",
    category: "entertainment",
    relatedSlugs: ["discord", "steam", "google", "reddit", "tiktok"],
    popularCountries: ["united-states", "canada", "united-kingdom", "germany", "poland"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Twitch",
      message: "Your Twitch verification code is 843921",
      code: "843921",
    },
  },
  {
    slug: "binance",
    name: "Binance",
    logo: "/services/binance.svg",
    category: "finance",
    relatedSlugs: ["paypal", "google", "apple", "telegram"],
    popularCountries: ["germany", "france", "brazil", "turkey", "india"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Binance",
      message: "[Binance] SMS verification code: 592731. Don't share it with anyone.",
      code: "592731",
    },
  },
  {
    slug: "ebay",
    name: "eBay",
    logo: "/services/ebay.svg",
    category: "shopping",
    relatedSlugs: ["aliexpress", "paypal", "shopee", "google"],
    popularCountries: ["united-states", "united-kingdom", "germany", "italy", "spain"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "eBay",
      message: "Your eBay security code is 271846. Do not share this code.",
      code: "271846",
    },
  },
  {
    slug: "reddit",
    name: "Reddit",
    logo: "/services/reddit.svg",
    category: "social",
    relatedSlugs: ["twitter", "discord", "twitch", "google"],
    popularCountries: ["united-states", "canada", "united-kingdom", "netherlands", "germany"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Reddit",
      message: "Your Reddit verification code is 617293",
      code: "617293",
    },
  },
  {
    slug: "fiverr",
    name: "Fiverr",
    logo: "/services/fiverr.svg",
    category: "other",
    relatedSlugs: ["google", "paypal", "twitter", "telegram"],
    popularCountries: ["united-states", "united-kingdom", "germany", "india", "philippines"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Fiverr",
      message: "Your Fiverr verification code is: 517284",
      code: "517284",
    },
  },
  {
    slug: "shopee",
    name: "Shopee",
    logo: "/services/shopee.svg",
    category: "shopping",
    relatedSlugs: ["aliexpress", "ebay", "grab", "line", "tiktok"],
    popularCountries: ["indonesia", "philippines", "thailand", "vietnam", "brazil"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Shopee",
      message: "382916 is your Shopee verification code. Do not share it with anyone.",
      code: "382916",
    },
  },
  {
    slug: "kakaotalk",
    name: "KakaoTalk",
    logo: "/services/kakaotalk.svg",
    category: "messaging",
    relatedSlugs: ["line", "wechat", "viber", "telegram", "zalo"],
    popularCountries: ["united-states", "canada", "united-kingdom", "germany", "indonesia"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "KakaoTalk",
      message: "[KakaoTalk] 4829 is your verification code.",
      code: "4829",
    },
  },
  {
    slug: "zalo",
    name: "Zalo",
    logo: "/services/zalo.svg",
    category: "messaging",
    relatedSlugs: ["line", "wechat", "viber", "telegram", "kakaotalk"],
    popularCountries: ["vietnam", "united-states", "thailand", "canada", "germany"],
    updatedAt: "2026-07-07",
    smsExample: {
      sender: "Zalo",
      message: "793145 is your Zalo activation code. Do not share it with anyone.",
      code: "793145",
    },
  },
];
