import { readdirSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";

export const LOCALES_DIR = join(__dirname, "..", "content", "locales");
export const BARREL = join(LOCALES_DIR, "index.generated.ts");

/** Locale folders on disk, registered or not. */
export function localeDirs(): string[] {
  return readdirSync(LOCALES_DIR)
    .filter((name) => statSync(join(LOCALES_DIR, name)).isDirectory())
    .sort();
}

/** File keys for one locale folder: "ui", "services/telegram", ... */
export function fileKeys(locale: string): string[] {
  const root = join(LOCALES_DIR, locale);
  const out: string[] = [];
  const walk = (dir: string) => {
    for (const name of readdirSync(dir).sort()) {
      const path = join(dir, name);
      if (statSync(path).isDirectory()) walk(path);
      else if (name.endsWith(".json")) out.push(relative(root, path).split(sep).join("/").replace(/\.json$/, ""));
    }
  };
  walk(root);
  return out;
}

export function renderBarrel(): string {
  const imports: string[] = [];
  const tables: string[] = [];
  let n = 0;
  for (const locale of localeDirs()) {
    const rows: string[] = [];
    for (const key of fileKeys(locale)) {
      const id = `f${n++}`;
      imports.push(`import ${id} from "./${locale}/${key}.json";`);
      rows.push(`    ${JSON.stringify(key)}: ${id},`);
    }
    tables.push(`  ${JSON.stringify(locale)}: {\n${rows.join("\n")}\n  },`);
  }
  return [
    "// Generated by `npm run i18n:sync` from the folders next to this file. Do not edit.",
    ...imports,
    "",
    "export const LOCALE_FILES: Record<string, Record<string, unknown>> = {",
    ...tables,
    "};",
    "",
  ].join("\n");
}
